import type { WeightedTask } from "./types";

export const dijkstraTask: WeightedTask = {
  id: "dijkstra-book",
  title: "Алгоритм Дейкстры",
  shortTitle: "Дейкстра",
  subtitle: "Самый дешевый путь в графе без отрицательных ребер",
  question: "Найти самый дешевый путь от книги до пианино.",
  start: "книга",
  finish: "пианино",
  nodes: [
    { id: "книга", label: "книга", x: 8, y: 42 },
    { id: "пластинка", label: "пластинка", x: 34, y: 20 },
    { id: "постер", label: "постер", x: 34, y: 64 },
    { id: "гитара", label: "гитара", x: 64, y: 20 },
    { id: "барабан", label: "барабан", x: 64, y: 64 },
    { id: "пианино", label: "пианино", x: 91, y: 42 },
  ],
  edges: [
    { from: "книга", to: "пластинка", weight: 5 },
    { from: "книга", to: "постер", weight: 0 },
    { from: "пластинка", to: "гитара", weight: 15 },
    { from: "пластинка", to: "барабан", weight: 20 },
    { from: "постер", to: "гитара", weight: 30 },
    { from: "постер", to: "барабан", weight: 35 },
    { from: "гитара", to: "пианино", weight: 20 },
    { from: "барабан", to: "пианино", weight: 10 },
  ],
  expected: [
    "Стоимость: 35",
    "Путь: книга -> пластинка -> барабан -> пианино",
    "Дейкстра выбирает вершину с минимальной известной стоимостью и релаксирует ее соседей.",
  ],
};

export const bellmanTasks: WeightedTask[] = [
  {
    id: "bf-01",
    title: "Задача 1. Базовый пример с отрицательным весом",
    shortTitle: "1. База",
    subtitle: "Кратчайшие пути от A до всех вершин",
    question: "Найдите кратчайшие пути от вершины A до всех вершин.",
    start: "A",
    nodes: [
      { id: "A", label: "A", x: 9, y: 44 },
      { id: "B", label: "B", x: 31, y: 22 },
      { id: "C", label: "C", x: 31, y: 66 },
      { id: "D", label: "D", x: 62, y: 44 },
      { id: "E", label: "E", x: 88, y: 44 },
    ],
    edges: [
      { from: "A", to: "B", weight: 4 },
      { from: "A", to: "C", weight: 2 },
      { from: "B", to: "C", weight: -1 },
      { from: "B", to: "D", weight: 5 },
      { from: "C", to: "D", weight: 8 },
      { from: "C", to: "E", weight: 10 },
      { from: "D", to: "E", weight: 2 },
    ],
    expected: [
      "A: 0",
      "B: 4",
      "C: 2 через A -> C",
      "D: 9 через A -> B -> D",
      "E: 11 через A -> B -> D -> E",
      "В PDF указано C: 3, но прямое ребро A -> C весит 2, поэтому корректный минимум равен 2.",
    ],
  },
  {
    id: "bf-02",
    title: "Задача 2. Обнаружение цикла отрицательного веса",
    shortTitle: "2. Цикл",
    subtitle: "Проверка отрицательного цикла, достижимого из A",
    question: "Определите, есть ли в графе цикл отрицательного веса, достижимый из A.",
    start: "A",
    nodes: [
      { id: "A", label: "A", x: 22, y: 24 },
      { id: "B", label: "B", x: 72, y: 24 },
      { id: "C", label: "C", x: 48, y: 72 },
    ],
    edges: [
      { from: "A", to: "B", weight: 1 },
      { from: "B", to: "C", weight: -1 },
      { from: "C", to: "A", weight: -1 },
    ],
    expected: ["Обнаружен цикл отрицательного веса: True", "Цикл: A -> B -> C -> A"],
  },
  {
    id: "bf-03",
    title: "Задача 3. Кратчайший путь с отрицательными ребрами",
    shortTitle: "3. S -> F",
    subtitle: "Восстановление пути от S до F",
    question: "Найдите кратчайший путь от S до F.",
    start: "S",
    finish: "F",
    nodes: [
      { id: "S", label: "S", x: 8, y: 45 },
      { id: "A", label: "A", x: 33, y: 25 },
      { id: "B", label: "B", x: 33, y: 65 },
      { id: "C", label: "C", x: 63, y: 65 },
      { id: "F", label: "F", x: 90, y: 45 },
    ],
    edges: [
      { from: "S", to: "A", weight: 4 },
      { from: "S", to: "B", weight: 3 },
      { from: "A", to: "B", weight: -2 },
      { from: "B", to: "A", weight: 1 },
      { from: "B", to: "C", weight: 2 },
      { from: "C", to: "F", weight: 1 },
      { from: "A", to: "F", weight: 5 },
    ],
    expected: ["Длина: 5", "Путь: S -> A -> B -> C -> F"],
  },
  {
    id: "bf-04",
    title: "Задача 4. Матрица смежности",
    shortTitle: "4. Матрица",
    subtitle: "Матрица переведена в список ребер",
    question: "Найдите кратчайшие пути от вершины 0.",
    start: "0",
    nodes: [
      { id: "0", label: "0", x: 18, y: 24 },
      { id: "1", label: "1", x: 74, y: 24 },
      { id: "2", label: "2", x: 74, y: 70 },
      { id: "3", label: "3", x: 18, y: 70 },
    ],
    edges: [
      { from: "0", to: "1", weight: 5 },
      { from: "1", to: "2", weight: -3 },
      { from: "2", to: "3", weight: 4 },
      { from: "3", to: "0", weight: 2 },
    ],
    expected: ["0: 0", "1: 5", "2: 2 через 0 -> 1 -> 2", "3: 6 через 0 -> 1 -> 2 -> 3"],
  },
  {
    id: "bf-05",
    title: "Задача 5. Восстановление пути",
    shortTitle: "5. Путь",
    subtitle: "Кратчайший путь от A до D",
    question: "Найдите кратчайший путь от A до D и выведите его.",
    start: "A",
    finish: "D",
    nodes: [
      { id: "A", label: "A", x: 12, y: 45 },
      { id: "B", label: "B", x: 38, y: 24 },
      { id: "C", label: "C", x: 38, y: 68 },
      { id: "D", label: "D", x: 80, y: 45 },
    ],
    edges: [
      { from: "A", to: "B", weight: 3 },
      { from: "A", to: "C", weight: 5 },
      { from: "B", to: "C", weight: -2 },
      { from: "B", to: "D", weight: 1 },
      { from: "C", to: "D", weight: 4 },
    ],
    expected: ["Длина: 4", "Путь: A -> B -> D"],
  },
  {
    id: "bf-06",
    title: "Задача 6. Недостижимый отрицательный цикл",
    shortTitle: "6. Недостижимый",
    subtitle: "Цикл есть, но он не достижим из A",
    question: "Найдите кратчайшие пути от A.",
    start: "A",
    nodes: [
      { id: "A", label: "A", x: 10, y: 28 },
      { id: "B", label: "B", x: 34, y: 28 },
      { id: "C", label: "C", x: 58, y: 28 },
      { id: "X", label: "X", x: 36, y: 72 },
      { id: "Y", label: "Y", x: 62, y: 72 },
    ],
    edges: [
      { from: "A", to: "B", weight: 2 },
      { from: "B", to: "C", weight: 3 },
      { from: "X", to: "Y", weight: 1 },
      { from: "Y", to: "X", weight: -5 },
    ],
    expected: ["A: 0", "B: 2", "C: 5", "X: ∞", "Y: ∞", "Отрицательный цикл X <-> Y не достижим из A."],
  },
  {
    id: "bf-07",
    title: "Задача 7. Сравнение с Дейкстрой",
    shortTitle: "7. Сравнение",
    subtitle: "Почему Дейкстра не подходит для отрицательных ребер",
    question: "Покажите результат Беллмана-Форда и объясните, почему Дейкстра здесь не подходит.",
    start: "A",
    nodes: [
      { id: "A", label: "A", x: 18, y: 48 },
      { id: "B", label: "B", x: 78, y: 26 },
      { id: "C", label: "C", x: 78, y: 72 },
    ],
    edges: [
      { from: "A", to: "B", weight: 10 },
      { from: "A", to: "C", weight: 5 },
      { from: "C", to: "B", weight: -8 },
    ],
    expected: ["A: 0", "B: -3 через A -> C -> B", "C: 5", "Дейкстра не рассчитана на отрицательные ребра."],
  },
  {
    id: "bf-08",
    title: "Задача 8. Многократные обновления",
    shortTitle: "8. Обновления",
    subtitle: "Расстояние до D обновляется бесконечно из-за отрицательного цикла",
    question: "Сколько раз обновится расстояние до D?",
    start: "A",
    nodes: [
      { id: "A", label: "A", x: 18, y: 24 },
      { id: "B", label: "B", x: 76, y: 24 },
      { id: "C", label: "C", x: 76, y: 72 },
      { id: "D", label: "D", x: 18, y: 72 },
    ],
    edges: [
      { from: "A", to: "B", weight: 1 },
      { from: "B", to: "C", weight: 1 },
      { from: "C", to: "D", weight: 1 },
      { from: "D", to: "A", weight: -4 },
    ],
    expected: ["Бесконечно", "Обнаружен отрицательный цикл: A -> B -> C -> D -> A", "Вес цикла: -1"],
  },
  {
    id: "bf-09",
    title: "Задача 9. Два отрицательных ребра",
    shortTitle: "9. Два ребра",
    subtitle: "Кратчайшие пути от S до всех вершин",
    question: "Найдите кратчайшие пути от S до всех вершин.",
    start: "S",
    nodes: [
      { id: "S", label: "S", x: 10, y: 46 },
      { id: "A", label: "A", x: 38, y: 25 },
      { id: "B", label: "B", x: 38, y: 68 },
      { id: "C", label: "C", x: 76, y: 46 },
    ],
    edges: [
      { from: "S", to: "A", weight: 3 },
      { from: "S", to: "B", weight: 4 },
      { from: "A", to: "B", weight: -2 },
      { from: "B", to: "C", weight: 1 },
      { from: "A", to: "C", weight: 5 },
    ],
    expected: ["S: 0", "A: 3", "B: 1 через S -> A -> B", "C: 2 через S -> A -> B -> C"],
  },
];
